/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction to Fynd Platform',
      collapsed: true,
      items: [
        'introduction/what-is-fp',
        'introduction/for-whom-is-fp',
        'introduction/fp-checklist'
      ]
    },
    {
      type: 'category',
      label: 'Initial Setup',
      collapsed: true,
      items: [
        'initial-setup/company-setup',
        'initial-setup/brand-setup',
        'initial-setup/location-setup'
      ]
    },
  ],
};
